### PR TITLE
Proposing a talk about using monorepos

### PR DESCRIPTION
**Pull request by edvald**
... with a focus on Node.js services and packages, and the specific issues involved for those.

Incidentally I'm working at Clue right across the hall in the same building. Let me know if it seems interesting. I'd also be happy to chat about other stuff we've worked on.

### CODE REVIEW

**Comment by rmehner** [comment]
Hey there, as this is an evening meetup, we only have so much slots and already had way more proposals. Given that you're next door at Clue anyway, how about our regular BerlinJS meetup that happens later the month? Would love to host you there :)

**Comment by rmehner** [comment]
Also, since this idea is floating around already, would you be able to make this a 5 minute lightning talk?

**Comment by edvald** [comment]
Hey - yeah no worries! Could do a lightning talk or do it next time, either way. Just let me know which one you prefer. I'll show up on Thursday either way, looks like it'll be a good event!

**Comment by rmehner** [comment]
We could also do both, since it's gonna be a different audience anyway. Lightning talks will be a bit spontaneous, depending on how the night goes. But if you have a 5 minute bit prepared, it won't hurt :)

**Comment by rmehner** [comment]
Since there's more people interested in Lightning talks, we'll very likely have a section for this. If you have something prepared for a 5 minute talk that is either a PDF, a website or a keynote / powerpoint file, we can do this :) (has to play on my computer, to reduce set up time)

Please confirm if you want to give this lightning talk, so I can announce you :)

**Comment by edvald** [comment]
Hey, sorry about the late response. Had quite a busy day, just now getting a bit of free time. I'd be happy to do a lightning talk though - I'll send some slides your way in about an hour. If it's too late, no worries, it'll be good preparation for a longer presentation either way :)

**Comment by edvald** [comment]
[2017-05-05 - Monorepos.pdf](https://github.com/berlinjs/jsconf2017-special/files/976968/2017-05-05.-.Monorepos.pdf)

Here are the slides.

**Comment by rmehner** [comment]
Thanks again and if you wanna do that on full length, here's our main repo: https://github.com/berlinjs/berlinjs.org

**Pull request closed without merging**
