### PR TITLE
Proposing "Standardizing READMEs for Great Good"

### PR DESCRIPTION
**Pull request by RichardLitt**
🌴  Thank you!

### CODE REVIEW

**Comment by RichardLitt** [comment]
Looks like we have a full docket of talks! Should I close this?

**Comment by RichardLitt** [comment]
Closing as per git commit message in 2930b23f6fbf5b04f45644dd696b4c9206034d50.

**Comment by rmehner** [comment]
@RichardLitt thanks for proposing, I was a bit caught up with life and didn't come back to you. Where are you located? Would it be possible for you to make it to our regular BerlinJS event later that month?

**Comment by RichardLitt** [comment]
No worries! Hope May Day was fun. I'm in Berlin until the 12th. Probably won't be able to make it.

I could do a lightning talk? 5 minutes should do the whole thing.

**Comment by rmehner** [comment]
> I could do a lightning talk? 5 minutes should do the whole thing.

That's actually a great idea. Please be prepared. I have no full schedule yet (this is very low key anyway), but it sounds like a good idea to have some Lightning talks.

**Comment by RichardLitt** [comment]
Already got the talk ready. Will come with laptop. Awesome! Thank you!

**Comment by rmehner** [comment]
Awesome. Would be super awesome if you'd have it ready as some OSX compatible format (Keynote, website, PDF, whatever) ... that way we would be able to reduce the needed setup.

**Comment by RichardLitt** [comment]
It's here: https://github.com/RichardLitt/talks/tree/master/standard-readme-dc. I was going to bring my MacBook Air. I can plug in directly, or you can git clone that and just open `index.html` in a browser.

**Comment by RichardLitt** [comment]
LMK if you want a blurb for the website.

**Comment by rmehner** [comment]
Alright, will prepare this on my laptop :) Will announce you at the beginning then and we'll have the lightning talk section at the end.

**Comment by RichardLitt** [comment]
Thanks @rmehner. Awesome.

**Comment by RichardLitt** [comment]
Sounds good! Thank you.

R

**Pull request closed without merging**
