### PR TITLE
Talk proposition "CSSinJS UVP"

### PR DESCRIPTION
**Pull request by kof**

### CODE REVIEW

**Comment by kof** [comment]
This talk didn't make it, right?

**Comment by rmehner** [comment]
> This talk didn't make it, right?

Hey there, sorry, wanted to get back yesterday, but then life happened. As we have limited slots (evening event) we couldn't take everyone and had to decide. However, your talk is quite interesting and as you are in Berlin, I'd love to have you over at the regular BerlinJS meetup. Is that possible? :)

**Comment by kof** [comment]
sure, will resubmit for the next meetup

**Comment by rmehner** [comment]
Awesome, thank you and looking forward already!

**Pull request closed without merging**
